import smtplib

from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

from app.config import (
    EMAIL_ADDRESS,
    EMAIL_PASSWORD,
    COMPANY_EMAIL
)


def send_support_email(

    customer_name: str,

    customer_email: str,

    summary: str

):

    subject = "New Customer Support Request"

    body = f"""
Hello GainOne Support Team,

A customer has requested human support.

----------------------------------------

Customer Name:
{customer_name}

Customer Email:
{customer_email}

----------------------------------------

AI Conversation Summary

{summary}

----------------------------------------

This email was automatically generated by
GainOne AI Customer Support System.

"""

    message = MIMEMultipart()

    message["From"] = EMAIL_ADDRESS

    message["To"] = COMPANY_EMAIL

    message["Subject"] = subject

    message.attach(

        MIMEText(body, "plain")

    )

    try:

        server = smtplib.SMTP(
            "smtp.gmail.com",
            587
        )

        server.starttls()

        server.login(
            EMAIL_ADDRESS,
            EMAIL_PASSWORD
        )

        server.sendmail(

            EMAIL_ADDRESS,

            COMPANY_EMAIL,

            message.as_string()

        )

        server.quit()

        print("Email Sent Successfully")

        return True

    except Exception as e:

        print("Email Error :", e)

        return False